EgyptExcavation/Controllers/BiologicalSamplesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EgyptExcavation.Models;
using Microsoft.AspNetCore.Authorization;

namespace EgyptExcavation.Controllers
{
    public class BiologicalSamplesController : Controller
    {
        // Connect to database
        private readonly EgyptContext _context;

        public BiologicalSamplesController(EgyptContext context)
        {
            _context = context;
        }

        [Authorize(Policy = "writepolicy")]
        // GET: BiologicalSamples
        // Not in use
        public async Task<IActionResult> Index()
        {
            return View(await _context.BiologicalSample.ToListAsync());
        }

        // GET: BiologicalSamples/Details/5
        // Shows details of an individual sample. You get here from the details of a burial listing
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var biologicalSample = await _context.BiologicalSample
                .FirstOrDefaultAsync(m => m.BiologicalId == id);
            if (biologicalSample == null)
            {
                return NotFound();
            }

            return View(biologicalSample);
        }

        // GET: BiologicalSamples/Create
        // Create form for new record
        [Authorize(Policy = "writepolicy")]
        public IActionResult Create(int? id = null)
        {
            string? burialId = null;
            if (id != null)
            {
                burialId = _context.Burial.Where(x => x.BurialIdInt == id).Select(x => x.BurialId).FirstOrDefault();
            }
            ViewBag.BurialId = burialId;
            return View();
        }

        // POST: BiologicalSamples/Create
        // Save new record
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "writepolicy")]
        public async Task<IActionResult> Create([Bind("BiologicalId,RackNumber,BagNumber,BurialId,LowPairNs,HighPairNs,BurialLocationNs,LowPairEw,HighPairEw,BurialLocationEw,BurialSubplot,BurialNumber,ClusterNumber,Date,PreviouslySampled,Notes,Initials,Column17")] BiologicalSample biologicalSample)
        {
            if (ModelState.IsValid)
            {
                _context.Add(biologicalSample);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Burials");
            }
            return View(biologicalSample);
        }

        // GET: BiologicalSamples/Edit/5
        // Edit form
        [Authorize(Policy = "writepolicy")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var biologicalSample = await _context.BiologicalSample.FindAsync(id);
            if (biologicalSample == null)
            {
                return NotFound();
            }
            return View(biologicalSample);
        }

        // POST: BiologicalSamples/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // Save edits
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "writepolicy")]
        public async Task<IActionResult> Edit(int id, [Bind("BiologicalId,RackNumber,BagNumber,BurialId,LowPairNs,HighPairNs,BurialLocationNs,LowPairEw,HighPairEw,BurialLocationEw,BurialSubplot,BurialNumber,ClusterNumber,Date,PreviouslySampled,Notes,Initials,Column17")] BiologicalSample biologicalSample)
        {
            if (id != biologicalSample.BiologicalId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(biologicalSample);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BiologicalSampleExists(biologicalSample.BiologicalId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(biologicalSample);
        }

        // GET: BiologicalSamples/Delete/5
        // Delete form
        [Authorize(Policy = "adminpolicy")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var biologicalSample = await _context.BiologicalSample
                .FirstOrDefaultAsync(m => m.BiologicalId == id);
            if (biologicalSample == null)
            {
                return NotFound();
            }

            return View(biologicalSample);
        }

        // POST: BiologicalSamples/Delete/5
        // Deletes record
        [Authorize(Policy = "adminpolicy")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var biologicalSample = await _context.BiologicalSample.FindAsync(id);
            var burialId = biologicalSample.BurialId;
            int burialIdInt = _context.Burial.Where(x => x.BurialId == burialId).Select(x => x.BurialIdInt).FirstOrDefault();
            _context.BiologicalSample.Remove(biologicalSample);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Burials");
        }

        private bool BiologicalSampleExists(int id)
        {
            return _context.BiologicalSample.Any(e => e.BiologicalId == id);
        }
    }
}

EgyptExcavation/Controllers/BurialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EgyptExcavation.Models;
using EgyptExcavation.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace EgyptExcavation 
{
    public class BurialsController : Controller
    {
        // Connect to Burials, Biological Samples, File Uploads
        private readonly EgyptContext _context;
        private readonly FileUploadsContext fileCtx;

        public BurialsController(EgyptContext context, FileUploadsContext fctx)
        {
            _context = context;
            fileCtx = fctx;
        }


        // GET: Burials
        // Returns Burials view. Includes pagination, filters, all the info that the cards need
        public IActionResult Index(string filterId, int pageNum = 0)
        {
            ViewBag.NavBar = "Browse";
            int pageSize = 5;

            //filters
            var filters = new Filters(filterId);
            ViewBag.Filters = filters;
            ViewBag.BurialSubplots = _context.Burial.Select(y => y.BurialSubplot).Distinct().ToList();
            ViewBag.Sex = _context.Burial.Select(y => y.GenderBodyCol).Distinct().ToList();
            ViewBag.HairColor = _context.Burial.Select(y => y.HairColor).Distinct().ToList();
            ViewBag.SampleTaken = _context.Burial.Select(y => y.SampleTaken).Distinct().ToList();
            ViewBag.AgeCode = _context.Burial.Select(y => y.AgeCode).Distinct().ToList();
            ViewBag.HeadDirection = _context.Burial.Select(y => y.HeadDirection).Distinct().ToList();
            ViewBag.YearFound = _context.Burial.Select(y => y.YearFound).Distinct().OrderBy(x => x).ToList();

            ViewBag.SexFilterValues = Filters.SexFilterValues;
            ViewBag.HairColorFilterValues = Filters.HairColorFilterValues;
            ViewBag.SampleTakenFilterValues = Filters.SampleTakenFilterValues;
            ViewBag.AgeCodeFilterValues = Filters.AgeCodeFilterValues;
            ViewBag.HeadDirectionFilterValues = Filters.HeadDirectionFilterValues;

            IQueryable<Burial> query = _context.Burial;

            if (filters.HasBurialSubplot)
            {
                query = query.Where(b => b.BurialSubplot == filters.BurialSubplot);
            }
            if (filters.HasSex)
            {
                query = query.Where(b => b.GenderBodyCol == filters.Sex);
            }
            if (filters.HasHairColor)
            {
                query = query.Where(b => b.HairColor == filters.HairColor);
            }
            if (filters.HasSampleTaken)
            {
                query = query.Where(b => b.SampleTaken == filters.SampleTaken);
            }
            if (filters.HasAgeCode)
            {
                query = query.Where(b => b.AgeCode == filters.AgeCode);
            }
            if (filters.HasHeadDirection)
            {
                query = query.Where(b => b.HeadDirection == filters.HeadDirection);
            }
            if (filters.HasYearFound)
            {
                query = query.Where(b => b.YearFound == filters.YearFound);
            }

            // pagination
            var skipNum = pageNum > 0 ? pageNum - 1 : pageNum;
            var burials = query.OrderByDescending(x => x.HasPhoto).Skip((skipNum) * pageSize).Take(pageSize).ToList();

            // put the data in a view model
            BrowseViewModel browseViewModel = new BrowseViewModel
            {
                Burials = burials,
                PageNumberingInfo = new PageNumberingInfo
                {
                    NumItemsPerPage = pageSize,
                    CurrentPage = pageNum,
                    // Takes count from filtered query instead of all items in database
                    TotalNumItems = query.Count()
                }
            };
            return View(browseViewModel);
        }

        // Creates the filter string for Burials index
        [HttpPost]
        public IActionResult Filter(string[] filter)
        {
            string newId = string.Join('-', filter);
            return RedirectToAction("Index", new { filterId = newId }); 
        }


        // GET: Burials/Details/5
        // Pull up the details for a burial. Includes links to file uploads and biological samples.
        public async Task<IActionResult> Details(int? id) 
        {
            ViewBag.NavBar = "Browse";

            if (id == null)
            {
                return NotFound();
            }

            var burial = _context.Burial
                .FirstOrDefault(m => m.BurialIdInt == id);
            if (burial == null)
            {
                return NotFound();
            }

            var samples = _context.BiologicalSample.Where(s => s.BurialId == burial.BurialId).ToList();
            ViewBag.Samples = samples;

            var uploads = fileCtx.Files.Where(t => t.BurialId == burial.BurialId).Select(x => x.DocumentId).ToList();
            ViewBag.Uploads = uploads;

            return View(burial);
        }

        // GET: Burials/Create
        // Create new burial record. Takes user to form
        [Authorize(Policy = "writepolicy")]
        public IActionResult Create()
        {
            ViewBag.NavBar = "Browse";

            return View();
        }

        // POST: Burials/Create
        // Get here from the form. Add the new burial to the database
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "writepolicy")]
        public async Task<IActionResult> Create([Bind("BurialId,BurialLocationNs,BurialLocationEw,LowPairNs,HighPairNs,LowPairEw,HighPairEw,BurialSubplot,BurialDepth,SouthToHead,SouthToFeet,WestToHead,WestToFeet,BurialSituation,LengthOfRemainsMeters,LengthOfRemainsCentimeters,BurialNumber,SampleNumber,GenderGe,GeFunctionTotal,GenderBodyCol,SexMethod,BasilarSuture,VentralArc,SubpubicAngle,SciaticNotch,PubicBone,PreaurSulcus,MedialIpRamus,DorsalPitting,ForamanMagnum,FemurHead,HumerusHead,Osteophytosis,PubicSymphysis,FemurLength,HumerusLength,TibiaLength,Robust,SupraorbitalRidges,OrbitEdge,ParietalBossing,Gonian,NuchalCrest,ZygomaticCrest,CranialSuture,MaximumCranialLength,MaximumCranialBreadth,BasionBregmaHeight,BasionNasion,BasionProsthionLength,BizygomaticDiameter,NasionProsthion,MaximumNasalBreadth,InterorbitalBreadth,ArtifactsDescription,HairColor,PreservationIndex,SampleTaken,HairTaken,SoftTissueTaken,BoneTaken,ToothTaken,TextileTaken,DescriptionOfTaken,ArtifactFound,EstimateAge,AgeMethod,AgeCode,EstimateLivingStature,ToothAttrition,ToothEruption,PathologyAnomalies,EpiphysealUnion,YearFound,MonthFound,DayFound,HeadDirection,Gamous,BurialIcon,BurialIcon2,BurialPreservation")] Burial burial)
        {
            ViewBag.NavBar = "Browse";

            if (ModelState.IsValid)
            {
                _context.Add(burial);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(burial);
        }

        // GET: Burials/Edit/5
        // Edit form for an existing burial. Auto-populates all the necessary fields
        [Authorize(Policy = "writepolicy")]
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.NavBar = "Browse";

            if (id == null)
            {
                return NotFound();
            }

            var burial = await _context.Burial.FindAsync(id);
            if (burial == null)
            {
                return NotFound();
            }
            return View(burial);
        }

        // POST: Burials/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // Save edits to a burial
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "writepolicy")]
        public async Task<IActionResult> Edit(int id, [Bind("BurialIdInt,BurialId,BurialLocationNs,BurialLocationEw,LowPairNs,HighPairNs,LowPairEw,HighPairEw,BurialSubplot,BurialDepth,SouthToHead,SouthToFeet,WestToHead,WestToFeet,BurialSituation,LengthOfRemainsMeters,LengthOfRemainsCentimeters,BurialNumber,SampleNumber,GenderGe,GeFunctionTotal,GenderBodyCol,SexMethod,BasilarSuture,VentralArc,SubpubicAngle,SciaticNotch,PubicBone,PreaurSulcus,MedialIpRamus,DorsalPitting,ForamanMagnum,FemurHead,HumerusHead,Osteophytosis,PubicSymphysis,FemurLength,HumerusLength,TibiaLength,Robust,SupraorbitalRidges,OrbitEdge,ParietalBossing,Gonian,NuchalCrest,ZygomaticCrest,CranialSuture,MaximumCranialLength,MaximumCranialBreadth,BasionBregmaHeight,BasionNasion,BasionProsthionLength,BizygomaticDiameter,NasionProsthion,MaximumNasalBreadth,InterorbitalBreadth,ArtifactsDescription,HairColor,PreservationIndex,SampleTaken,HairTaken,SoftTissueTaken,BoneTaken,ToothTaken,TextileTaken,DescriptionOfTaken,ArtifactFound,EstimateAge,AgeMethod,AgeCode,EstimateLivingStature,ToothAttrition,ToothEruption,PathologyAnomalies,EpiphysealUnion,YearFound,MonthFound,DayFound,HeadDirection,Gamous,BurialIcon,BurialIcon2,BurialPreservation")] Burial burial)
        {
            ViewBag.NavBar = "Browse";
            if (id != burial.BurialIdInt)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(burial);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BurialExists(burial.BurialIdInt))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

EgyptExcavation/Views/Home/AddRecord.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Add Record";
}

<link rel="icon" href="~/img/icon.jpg" type="image/icon type">


<div class="row">
    <div class="col-4 text-center">
        <h1>Add a Burial Record</h1>
        <a class="btn btn-success" asp-controller="Burials" asp-action="Create">New Burial</a>
    </div>
    <div class="col-4 text-center">
        <h1>Add a Biological Sample</h1>
        <a class="btn btn-success" asp-controller="BiologicalSamples" asp-action="Create">New Sample</a>
    </div>
    <div class="col-4 text-center">
        <h1>Upload Field Notes or Photos </h1>
        <a class="btn btn-success" asp-controller="Home" asp-action="UploadFile">New Upload</a>
    </div>
</div>

EgyptExcavation/Views/Home/DeleteUploadConfirmation.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Files

<div class="text-center">
    <h1>File Upload</h1>
    <h3 class="mb-2 text-muted">File ID #@Model.DocumentId-- @Model.BurialId</h3>
    <p>Do you really want to delete this record?</p>
    <a href="javascript:history.back(2)" class="btn btn-primary">Back to Burial Listing</a>
    <a asp-controller="Home" asp-action="DeleteUpload" asp-route-id="@Model.DocumentId" class="btn btn-danger">Delete</a>
    <br />

    @if (Model.FileType.Contains("jpg") || Model.FileType.Contains("png") || Model.FileType.Contains("JPG") || Model.FileType.Contains("PNG"))
    {
        <img src="@Model.GetImageFromByteArray()" />
    }
</div> 

EgyptExcavation/Views/Home/FileUploadSuccessful.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="text-center">
    <h1>File Upload Successful</h1>
    <a asp-controller="Home" asp-action="UploadFile" class="btn btn-success">Add Another File</a>
    <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Home</a>
</div>

EgyptExcavation/Views/Home/Gallery.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
        ViewData["Title"] = "Gallery";
}

<link rel="icon" href="~/img/icon.jpg" type="image/icon type">

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<!--<h1 class="w3-center">Gallery</h1>-->

<div class="w3-content w3-display-container text-center">
    <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
    <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
    <div class="mySlides">
        <img src="~/img/MicrosoftTeams-image.png" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/13 February 2007 026.jpg" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/13 February 2007 070.jpg" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/13 February 2007 087.jpg" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/150-160N 0-10E SW Burial 5 - Skull B.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/150-160N 50-60E SW Burial 26 - skull.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/190-200N 30-40E NE Burial 11 G.jpg" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/190-200N 30-40E NE Burial 18 -- Nail A.jpg" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/21. B.5.7 140-160N 50-60E NW Burial 28.jpg" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/25. B.3.32 1401-50N 50-60E NW Burial 18.jpg" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/65-back.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/65-bottom.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/65-bottom2.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/65-front.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/65-lft-side.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/65-top.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/AM130235.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/Area 7 -- Stone A.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCF8496.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN0184.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN0219.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN0220.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN0221.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN0233.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN0250.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN3426.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN3436.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN9864.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN9881.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/FT130345.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/FT270435.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/IMG_0967.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/FT270445.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/IMG_0968.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/IMG_2969.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/mummy.png" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/P2160230.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/PE220251 (2).JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/PE220275 (2).JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/Slide19.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/Slide6.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/Slide7.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN3977.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/IMG_0431.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSC_0007.jpg" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN0004.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN0967.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN1000.JPG" />
        <p></p>
    </div>
    <div class="mySlides">
        <img src="~/img/DSCN0316.JPG" />
        <p></p>
    </div>
</div>

EgyptExcavation/Views/Home/ImageUploads.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<Files> 

@foreach (var img in Model)
{
    @if (img.FileType.Contains("jpg") || img.FileType.Contains("png") || img.FileType.Contains("JPG") || img.FileType.Contains("PNG"))
    {
                    <img src="@img.GetImageFromByteArray()" />
                }
}

EgyptExcavation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Way of the Water Buffalo";
}


<div class="container">
    <h1>Way of the Water Buffalo</h1>
    <br />
    <img src="~/img/IMG_0968.JPG" />
    <br />
    <br />
    <p class="lead font-weight-normal">
        Fag el-Gamous (which means Way of the Water Buffalo) is a large and important cemetery in Egypt that has been under archeological investigation (primarily by BYU researchers) for over 25 years. The excavation has garnered international attention because of the interesting insights gained by studying the Fag el-Gamous mummies. Detailed background information on this site can be found in the academic article <a href="https://www.sciencedirect.com/science/article/pii/S2352409X15000188">“Rethinking burial dates at a Graeco-Roman Cemetery: Fag el-Gamous, Fayoum, Egypt.”</a>
    </p>
    <div class="text-center">
        <a asp-action="Index" asp-controller="Burials" class="btn btn-primary">Browse Burial Info</a>
    </div>
    <br />
    <br />

</div>

EgyptExcavation/Views/Home/UploadDetails.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Files

<div class="text-center">
    <h1>File Upload</h1>
    <h3 class="mb-2 text-muted">File ID #@Model.DocumentId-- @Model.BurialId</h3>
    @if (Model.FileType.Contains("jpg") || Model.FileType.Contains("png") || Model.FileType.Contains("JPG") || Model.FileType.Contains("PNG"))
    {
        <img src="@Model.GetImageFromByteArray()" />
    }
</div> 

EgyptExcavation/Views/Home/UploadFile.cshtml
@model EgyptExcavation.Models.Files

@{
    ViewData["Title"] = "Upload File";
}

<link rel="icon" href="~/img/icon.jpg" type="image/icon type">

<h1>Upload Field Notes or Photos Here</h1>


<!-- Upload  -->
<form asp-controller="Home" asp-action="UploadFile" id="file-upload-form" class="uploader" method="post" enctype="multipart/form-data">

    <div class="container">
        <div>
            <div class="row">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="row ">
                        <div class="col-6">
                            <ul class="list-group">
                                <li class="form-group list-group-item">
                                    <label class="control-label text-center" style="text-decoration: underline;" asp-for="BurialId"><h3><b>Burial Id</b></h3></label>
                                    <p><b>Please the following format:</b> </p>
                                    <p>N 190/200 E 40/50 SE #9</p>
                                    <input asp-for="BurialId" class="form-control" value="@ViewBag.BurialId"/>
                                    <span asp-validation-for="BurialId" class="text-danger"></span>
                                    <input asp-for="DocumentId" class="form-control" type="hidden" />
                                    <span asp-validation-for="DocumentId"></span>
                                </li>
                            </ul>
                        </div>
                        <div class="col-6">
                            <div class="col-12 list-group">
                                <div class="form-group list-group-item">
                                    <div class="container" style="padding:2%">
                                        <br />
                                        <div class="form-group">
                                            <div class="col-md-10">
                                                <input name="files" type="file" asp-for="DataFiles" />
                                                <span asp-validation-for="DataFiles"></span>
                                            </div>
                                        </div>
                                        <br />
                                        <br />
                                        <input class="btn btn-primary" type="submit">
                                        <br />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                  
                <br />
            </div>
        </div>
    </div>

    <br />
</form>