EgyptExcavation/Controllers/BurialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EgyptExcavation.Models;
using EgyptExcavation.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace EgyptExcavation 
{
    public class BurialsController : Controller
    {
        // Connect to Burials, Biological Samples, File Uploads
        private readonly EgyptContext _context;
        private readonly FileUploadsContext fileCtx;

        public BurialsController(EgyptContext context, FileUploadsContext fctx)
        {
            _context = context;
            fileCtx = fctx;
        }


        // GET: Burials
        // Returns Burials view. Includes pagination, filters, all the info that the cards need
        public IActionResult Index(string filterId, int pageNum = 0)
        {
            ViewBag.NavBar = "Browse";
            int pageSize = 5;

            //filters
            var filters = new Filters(filterId);
            ViewBag.Filters = filters;
            ViewBag.BurialSubplots = _context.Burial.Select(y => y.BurialSubplot).Distinct().ToList();
            ViewBag.Sex = _context.Burial.Select(y => y.GenderBodyCol).Distinct().ToList();
            ViewBag.HairColor = _context.Burial.Select(y => y.HairColor).Distinct().ToList();
            ViewBag.SampleTaken = _context.Burial.Select(y => y.SampleTaken).Distinct().ToList();
            ViewBag.AgeCode = _context.Burial.Select(y => y.AgeCode).Distinct().ToList();
            ViewBag.HeadDirection = _context.Burial.Select(y => y.HeadDirection).Distinct().ToList();
            ViewBag.YearFound = _context.Burial.Select(y => y.YearFound).Distinct().OrderBy(x => x).ToList();

            ViewBag.SexFilterValues = Filters.SexFilterValues;
            ViewBag.HairColorFilterValues = Filters.HairColorFilterValues;
            ViewBag.SampleTakenFilterValues = Filters.SampleTakenFilterValues;
            ViewBag.AgeCodeFilterValues = Filters.AgeCodeFilterValues;
            ViewBag.HeadDirectionFilterValues = Filters.HeadDirectionFilterValues;

            IQueryable<Burial> query = _context.Burial;

            if (filters.HasBurialSubplot)
            {
                query = query.Where(b => b.BurialSubplot == filters.BurialSubplot);
            }
            if (filters.HasSex)
            {
                query = query.Where(b => b.GenderBodyCol == filters.Sex);
            }
            if (filters.HasHairColor)
            {
                query = query.Where(b => b.HairColor == filters.HairColor);
            }
            if (filters.HasSampleTaken)
            {
                query = query.Where(b => b.SampleTaken == filters.SampleTaken);
            }
            if (filters.HasAgeCode)
            {
                query = query.Where(b => b.AgeCode == filters.AgeCode);
            }
            if (filters.HasHeadDirection)
            {
                query = query.Where(b => b.HeadDirection == filters.HeadDirection);
            }
            if (filters.HasYearFound)
            {
                query = query.Where(b => b.YearFound == filters.YearFound);
            }

            // pagination
            var skipNum = pageNum > 0 ? pageNum - 1 : pageNum;
            var burials = query.OrderByDescending(x => x.HasPhoto).Skip((skipNum) * pageSize).Take(pageSize).ToList();

            // put the data in a view model
            BrowseViewModel browseViewModel = new BrowseViewModel
            {
                Burials = burials,
                PageNumberingInfo = new PageNumberingInfo
                {
                    NumItemsPerPage = pageSize,
                    CurrentPage = pageNum,
                    // Takes count from filtered query instead of all items in database
                    TotalNumItems = query.Count()
                }
            };
            return View(browseViewModel);
        }

        // Creates the filter string for Burials index
        [HttpPost]
        public IActionResult Filter(string[] filter)
        {
            string newId = string.Join('-', filter);
            return RedirectToAction("Index", new { filterId = newId }); 
        }


        // GET: Burials/Details/5
        // Pull up the details for a burial. Includes links to file uploads and biological samples.
        public async Task<IActionResult> Details(int? id) 
        {
            ViewBag.NavBar = "Browse";

            if (id == null)
            {
                return NotFound();
            }

            var burial = _context.Burial
                .FirstOrDefault(m => m.BurialIdInt == id);
            if (burial == null)
            {
                return NotFound();
            }

            var samples = _context.BiologicalSample.Where(s => s.BurialId == burial.BurialId).ToList();
            ViewBag.Samples = samples;

            var uploads = fileCtx.Files.Where(t => t.BurialId == burial.BurialId).Select(x => x.DocumentId).ToList();
            ViewBag.Uploads = uploads;

            return View(burial);
        }

        // GET: Burials/Create
        // Create new burial record. Takes user to form
        [Authorize(Policy = "writepolicy")]
        public IActionResult Create()
        {
            ViewBag.NavBar = "Browse";

            return View();
        }

        // POST: Burials/Create
        // Get here from the form. Add the new burial to the database
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "writepolicy")]
        public async Task<IActionResult> Create([Bind("BurialId,BurialLocationNs,BurialLocationEw,LowPairNs,HighPairNs,LowPairEw,HighPairEw,BurialSubplot,BurialDepth,SouthToHead,SouthToFeet,WestToHead,WestToFeet,BurialSituation,LengthOfRemainsMeters,LengthOfRemainsCentimeters,BurialNumber,SampleNumber,GenderGe,GeFunctionTotal,GenderBodyCol,SexMethod,BasilarSuture,VentralArc,SubpubicAngle,SciaticNotch,PubicBone,PreaurSulcus,MedialIpRamus,DorsalPitting,ForamanMagnum,FemurHead,HumerusHead,Osteophytosis,PubicSymphysis,FemurLength,HumerusLength,TibiaLength,Robust,SupraorbitalRidges,OrbitEdge,ParietalBossing,Gonian,NuchalCrest,ZygomaticCrest,CranialSuture,MaximumCranialLength,MaximumCranialBreadth,BasionBregmaHeight,BasionNasion,BasionProsthionLength,BizygomaticDiameter,NasionProsthion,MaximumNasalBreadth,InterorbitalBreadth,ArtifactsDescription,HairColor,PreservationIndex,SampleTaken,HairTaken,SoftTissueTaken,BoneTaken,ToothTaken,TextileTaken,DescriptionOfTaken,ArtifactFound,EstimateAge,AgeMethod,AgeCode,EstimateLivingStature,ToothAttrition,ToothEruption,PathologyAnomalies,EpiphysealUnion,YearFound,MonthFound,DayFound,HeadDirection,Gamous,BurialIcon,BurialIcon2,BurialPreservation")] Burial burial)
        {
            ViewBag.NavBar = "Browse";

            if (ModelState.IsValid)
            {
                _context.Add(burial);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(burial);
        }

        // GET: Burials/Edit/5
        // Edit form for an existing burial. Auto-populates all the necessary fields
        [Authorize(Policy = "writepolicy")]
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.NavBar = "Browse";

            if (id == null)
            {
                return NotFound();
            }

            var burial = await _context.Burial.FindAsync(id);
            if (burial == null)
            {
                return NotFound();
            }
            return View(burial);
        }

        // POST: Burials/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // Save edits to a burial
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "writepolicy")]
        public async Task<IActionResult> Edit(int id, [Bind("BurialIdInt,BurialId,BurialLocationNs,BurialLocationEw,LowPairNs,HighPairNs,LowPairEw,HighPairEw,BurialSubplot,BurialDepth,SouthToHead,SouthToFeet,WestToHead,WestToFeet,BurialSituation,LengthOfRemainsMeters,LengthOfRemainsCentimeters,BurialNumber,SampleNumber,GenderGe,GeFunctionTotal,GenderBodyCol,SexMethod,BasilarSuture,VentralArc,SubpubicAngle,SciaticNotch,PubicBone,PreaurSulcus,MedialIpRamus,DorsalPitting,ForamanMagnum,FemurHead,HumerusHead,Osteophytosis,PubicSymphysis,FemurLength,HumerusLength,TibiaLength,Robust,SupraorbitalRidges,OrbitEdge,ParietalBossing,Gonian,NuchalCrest,ZygomaticCrest,CranialSuture,MaximumCranialLength,MaximumCranialBreadth,BasionBregmaHeight,BasionNasion,BasionProsthionLength,BizygomaticDiameter,NasionProsthion,MaximumNasalBreadth,InterorbitalBreadth,ArtifactsDescription,HairColor,PreservationIndex,SampleTaken,HairTaken,SoftTissueTaken,BoneTaken,ToothTaken,TextileTaken,DescriptionOfTaken,ArtifactFound,EstimateAge,AgeMethod,AgeCode,EstimateLivingStature,ToothAttrition,ToothEruption,PathologyAnomalies,EpiphysealUnion,YearFound,MonthFound,DayFound,HeadDirection,Gamous,BurialIcon,BurialIcon2,BurialPreservation")] Burial burial)
        {
            ViewBag.NavBar = "Browse";
            if (id != burial.BurialIdInt)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(burial);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BurialExists(burial.BurialIdInt))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

EgyptExcavation/Controllers/RoleController.cs
using EgyptExcavation.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EgyptExcavation.Controllers
{
    // The majority of this controller is generated by Microsoft.AspNetCore.Identity. We add policy requirements so no tom-foolery happens
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> roleManager;
        UserManager<IdentityUser> userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [Authorize(Policy = "adminpolicy")]
        public IActionResult Index()
        {
            ViewBag.NavBar = "Roles";
            var roles = roleManager.Roles.ToList();
            return View(roles);
        }

        [Authorize(Policy = "adminpolicy")]
        public IActionResult Create()
        {
            ViewBag.NavBar = "Roles";
            return View(new IdentityRole());
        }

        [Authorize(Policy = "adminpolicy")]
        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            ViewBag.NavBar = "Roles";
            await roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
        [Authorize(Policy = "adminpolicy")]
        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            // Find the role by Role ID
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }

            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };

            // Retrieve all the Users
            foreach (var user in userManager.Users)
            {
                // If the user is in this role, add the username to
                // Users property of EditRoleViewModel. This model
                // object is then passed to the view for display
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.Email);
                }
            }

            return View(model);
        }
        [Authorize(Policy = "adminpolicy")]
        // This action responds to HttpPost and receives EditRoleViewModel
        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;

                // Update the Role using UpdateAsync
                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
        }
        [Authorize(Policy = "adminpolicy")]
        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            var model = new List<UserRoleViewModel>();

            foreach (var user in userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }

                model.Add(userRoleViewModel);
            }

            return View(model);
        }
        [Authorize(Policy = "adminpolicy")]
        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction("EditRole", new { Id = roleId });
                }
            }

            return RedirectToAction("EditRole", new { Id = roleId });
        }
    }
}

EgyptExcavation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="img/icon.jpg" type="image/icon type">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/header.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/base.css">
    <link rel="stylesheet" href="~/css/responsive.css" media="all and (min-width:16em)">
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
</head>

@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<body>

    <header id="main-header" role="banner">
        <div id="header-top" class="wrapper">
            <div style="padding:2%" class="logo" id="logo">

                <a href="http://www.byu.edu/" title="Home" rel="home">
                    <img src="https://religion.byu.edu/sites/default/themes/7.x-old/logo.png" alt="BYU Logo">
                </a>
                <div style="padding-left:2%; padding-top:1%">
                    <a asp-action="Index" asp-controller="Home"><h2 style="color: white; font-family: 'Palatino Linotype';">Fag el-Gamous</h2></a>
                </div>
                @*<partial name="_LoginPartial" />*@


            </div>
            
            <!--search
    <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
        -->
        </div>
    </header>


    <div class="nav-container">
        <!-- Primary Nav-->
        <nav id="primary-nav" role="navigation">

            <ul>
                <li>
                    <a asp-controller="Home" asp-action="Index" class=" @if (ViewBag.NavBar == "Home") { <text>current</text> }">Home</a>
                </li>
                <li><a asp-controller="Burials" asp-action="Index" class=" @if (ViewBag.NavBar == "Browse") { <text>current</text> } ">Browse Burials</a></li>
                <li><a asp-controller="Home" asp-action="Gallery" class=" @if (ViewBag.NavBar == "Gallery") { <text>current</text> } ">Gallery</a></li>

                @if (User.Identity.IsAuthenticated)
                {
                    @if (User.IsInRole("Admin") || User.IsInRole("Researcher"))
                    {
                        <li><a asp-controller="Home" asp-action="AddRecord" class="@if (ViewBag.NavBar == "AddRecord") { <text>current</text> }">Add Record</a></li>
                    }}
                <li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-controller="Role" asp-action="Index" class="@if (ViewBag.NavBar == "Roles") { <text>current</text> }">Roles</a>}}
                </li>
            </ul>
            @if (SignInManager.IsSignedIn(User))
             {
                <ul>
                    <li style="float:right;" class="">
                        <form id="logoutForm" class="" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                            <button id="logout" type="submit" style="padding-top:7px; font-family: 'Whitney SSm A', 'Whitney SSm B' , 'OpenSans' , 'Thonburi' , 'DroidSans' , 'Droid Sans' , 'sans-serif' , 'Lucida Grande' , 'Lucida Sans Unicode' , 'Lucida Sans' , Helvetica, Arial, sans-serif;
                                    font-weight: 500;" class="nav-link btn btn-link text-white">
                                Logout
                            </button>
                        </form>
                    </li>
                    <li style="float: right;">
                        <a id="manage" class="text-white" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @UserManager.GetUserName(User)!</a>
                    </li>

                </ul>
            }
            else
            {
                <ul>
                    <li style="float:right; background-image: linear-gradient(to bottom, #628cb6, #336699);">
                        <a class="" id="login" asp-area="Identity" asp-page="/Account/Login">Researcher Portal</a>
                    </li>
                    

                </ul> 
            }
        </nav>
    </div>

    <div id="content" role="main">
        <!-- Breadcrumb-->
        <ul class="breadcrumb">
            @*<li>
                    <div class="dropdown">
                        <a href="" data-toggle="dropdown" class="home dropdown-toggle needsclick"><i class="fa fa-home fa-lg"></i><span class="visuallyhidden">Home</span><i class="fa fa-caret-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="www.byu.edu">BYU Home</a></li>
                            <li><a href="#">Home Page</a></li>
                            <li><a href="#">Two Pages Above</a></li>
                        </ul><i class="divider fa fa-angle-right"></i>
                    </div>
                </li>
                <li><a href="#">One page above</a><i class="divider fa fa-angle-right"></i></li>
                <li class="active">Current Page</li>*@
        </ul>
        <div class="text-center">
            <!--<h1>@ViewBag.Title</h1>-->
        </div>
        <br />
        @RenderBody()
    </div>



    <!--footer-->
    <footer id="page-footer" role="contentinfo">
        <div id="footer-links">
            <div class=" row wrapper">
                <div class="col-4 alpha">
                    <h2 class="text-center">Contact</h2><a href="">Joseph Smith Building Provo, Utah 84602</a><a href="">Open: Monday-Friday 8:00 AM - 5:00 PM Closed: Holidays</a><a href="">Phone: 801-422-2735</a><a href="https://religion.byu.edu/contact">Send a Message</a>
                </div>
                <div class="col-4">
                    <h2 class="text-center">Religious Education</h2><a href="https://religion.byu.edu/event/egyptian-excavation-exhibit">BYU Article on Exhibit</a>
                </div>
                <div class="col-4 omega">
                    <h2 class="text-center">Related Links</h2><a href="https://www.sciencedirect.com/science/article/pii/S2352409X15000188">Rethinking Burial Dates</a><a href="https://brill.com/view/title/35250">Fag el-Gamous Cementary</a><a href="https://scholarsarchive.byu.edu/facpub/3562/">The Seila Pyramid</a><a href="https://www.nbcnews.com/science/weird-science/million-mummy-cemetery-unearthed-egypt-includes-childs-remains-n269561">Mummy News</a>
                </div>
            </div>
        </div>
        <div style="background-color:#002E5D" id="footer-bottom">
            @*<div class="wrapper clearfix text-center">
                    <a  style="color:white" id="lds" href="http://byu.edu/">Brigham Young University</a>
                </div>*@
            <h3 class="text-center" style="color:white" asp-controller="Home" asp-action="Privacy">Privacy Notice</h3>
        </div>

    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>